### PR TITLE
feat: user defined ports and healthcheck-probes

### PR DESCRIPTION
**Pull request by h1manshu98**
## What
- User can define their own
  - `containerPort:` & `targetPort:` if user does not provide any values then a default value will be used
  - `livenessProbe` & `readinessProbe` 

- Removed condition that makes passing `resources: limit & request` mandatory.
- Removed default `KEY: "VALUE"` pair from Secret & ConfigMap.
- Updated condition to control `VirtualService` creation.
- Updated `ServiceMonitor` yaml to fix below warning comes after successful chart installation.
```bash
## [warning]Capturing deployment metadata failed with error: TypeError: Cannot read property 'kind' of null
```

### CODE REVIEW

**Review by d4kverma — APPROVED** [review]
LGTM

**Comment by nileshgadgi** [comment]
What is the use of config/override-values.yml file here?
I can see that it's not mentioned in the official folder structure of helm chart. https://helm.sh/docs/topics/charts/

**Review by vaibhav7797 — APPROVED** [review]
LGTM!

**Comment by h1manshu98** [comment]
> What is the use of config/override-values.yml file here? I can see that it's not mentioned in the official folder structure of helm chart. https://helm.sh/docs/topics/charts/

@nileshgadgi 
We are using this override-values.yaml in our checkov github-action.
As per the default HelmChart structure it should not be there, but to follow HelmChart best practices we should create a new override-values.yaml instead of updating the default values.yaml.

**Review by anmolnagpal — APPROVED** [review]

**Pull request merged**
